name: 'Run CI jobs - lint and tests'
run-name: 'Run CI jobs - lint and tests'
on:
    pull_request
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout repo'
              uses: actions/checkout@v4
            - name: 'Setup node'
              uses: actions/setup-node@v4
              with:
                node-version: latest
            - name: 'Install dependencies - Yarn'
              run: yarn --frozen-lockfile
            - name: 'Eslint'
              run: 'yarn lint'
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout repo'
              uses: actions/checkout@v4
            - name: 'Setup node'
              uses: actions/setup-node@v4
              with:
                node-version: latest
            - name: 'Install dependencies - Yarn'
              run: yarn --frozen-lockfile
            - name: 'Test'
              run: yarn test
